clc;clear;close all;
img = double(imread('input\checker.png'));
[height, width] = size(img);
sigma_d = 0.7;
sigma_i = 1;
trace_weight = 0.05;
[points, R] = harris_detector(img, sigma_d, sigma_i, trace_weight);
imagesc(R);
pause;
imagesc(img);
colormap('gray');
hold on;
plot(points(:, 1), points(:, 2), 'b+', 'MarkerSize', 5);
plot(points(:, 1), points(:, 2), 'yo', 'MarkerSize', 5);
hold off;
pause;